# Используем Node.js образ для Production
FROM node:22-alpine

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем package.json и устанавливаем зависимости
COPY package*.json ./
RUN npm install

# Копируем остальные файлы проекта
COPY . .

# Удаляем development зависимости для production
RUN npm prune --production

# Открываем порт для сервера
EXPOSE 3000

# Команда для запуска Express сервера на TypeScript
CMD ["npx", "ts-node", "server.ts"]