# Dockerfile.dev для express
FROM node:22-alpine

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем package.json и устанавливаем зависимости
COPY package*.json ./
RUN npm install

# Копируем остальные файлы проекта
COPY . .

# Открываем порт для сервера
EXPOSE 3000

# Команда для запуска Express сервера
CMD ["npx", "ts-node", "server.ts"]
