FROM node:20-alpine

WORKDIR /app

# Копируем только package*.json для кэширования зависимостей
COPY package.json .

# Устанавливаем зависимости
RUN npm install

# Копируем оставшиеся файлы
COPY . .

# Открываем порт
EXPOSE 3000

CMD ["npx", "ts-node", "server.ts"]
