services:
    # express-app:
    #     build:
    #         context: ./express
    #         dockerfile: Dockerfile.prod
    #     container_name: express_app
    #     restart: always
    #     environment:
    #         NODE_ENV: production
    #     ports:
    #         - "3000:3000"
    #     volumes:
    #         - shared-data:/app/public

    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile.prod
        container_name: nginx_server
        # user: "www-data"
        restart: always
        ports:
            - "80:80"
            # - "443:443"
        volumes:
            # - ./nginx/certs:/etc/letsencrypt
            - ./nginx/html:/usr/share/nginx/html
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            # - /var/cache/nginx:/var/cache/nginx
            # - shared-data:/app/public
        # depends_on:
        #     - express-app

    # certbot:
    #     image: certbot/certbot
    #     container_name: certbot
    #     volumes:
    #         - ./nginx/certs:/etc/letsencrypt
    #         - ./nginx/www:/var/www/certbot
    #     entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 6h & wait $${!}; certbot renew; done;'"

volumes:
    nginx_certs:
    nginx_www:
    shared-data:
