services:
    react-app:
        build:
            context: ./react
            dockerfile: Dockerfile.dev
        ports:
            - "5173:5173"
        volumes:
            - ./react:/app # Монтируем только исходники
            - /app/node_modules # Не монтируем локальные node_modules
            - shared-data:/app/public # Общий volume для данных JSON
        environment:
            - CHOKIDAR_USEPOLLING=true
        restart: on-failure
        depends_on:
            - express-app

    express-app:
        build:
            context: ./express
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        volumes:
            - ./express:/app # Монтируем только исходники
            - /app/node_modules # Не монтируем локальные node_modules
            - shared-data:/app/public # Общий volume для данных JSON
        restart: on-failure

volumes:
    shared-data:
