services:
    react-app:
        build:
            context: ./react
            dockerfile: Dockerfile.dev
        ports:
            - "5173:5173"
        volumes:
            - ./react:/app
            - node_modules:/app/node_modules
            - shared-data:/app/public # Общий volume для доступа к данным JSON
        environment:
            - CHOKIDAR_USEPOLLING=true
        command: npm run dev -- --host
        restart: on-failure # Перезапуск при сбоях

    express-app:
        build:
            context: ./express
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        volumes:
            - ./express:/app
            - /app/node_modules
            - shared-data:/app/public # Общий volume для данных JSON
        command: npx ts-node server.ts
        restart: on-failure # Перезапуск при сбоях

volumes:
    node_modules:
    shared-data: # Определяем volume для общего файла
