version: "3.8"

services:
    react-app:
        build:
            context: ./react
            dockerfile: Dockerfile.dev
        ports:
            - "5173:5173" # Пробрасываем порт 5173 для Vite
        volumes:
            - ./react:/app # Монтируем локальную папку с исходным кодом для hot-reload
            - node_modules:/app/node_modules # Volume для node_modules, специфичный для контейнера
        environment:
            - CHOKIDAR_USEPOLLING=true # Включаем polling для отслеживания изменений
        command: npm run dev -- --host # Добавляем флаг --host для доступа к Vite извне

volumes:
    node_modules: # Определяем named volume для node_modules
