# docker-compose.yml

version: "3.8"

services:
    react:
        build:
            context: ./react
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        volumes:
            - ./react:/app
            - /app/node_modules
        command: ["npm", "run", "dev", "--", "--port", "3000"]

    nginx:
        image: nginx:alpine
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./react/dist:/usr/share/nginx/html
        ports:
            - "80:80"
        depends_on:
            - react
