FROM node:20-slim

WORKDIR /app

# Копируем package.json и package-lock.json, чтобы кэшировать зависимости
COPY package.json .

# Устанавливаем зависимости
RUN npm install
# Копируем остальные файлы
COPY . .

# Открываем порт
EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]
